name: Packer Build

on:
  push:
    branches:
      - stage
      - prod

jobs:
  packer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Packer
        uses: hashicorp/setup-packer@v1
        with:
          packer_version: latest

      - name: Validate Packer template
        run: packer validate webapp.json

      - name: Build Packer image
        run: packer build webapp.json

      - name: Upload AMI ID to Terraform Cloud
        run: |
          AMI_ID=$(packer build -machine-readable webapp.json | awk -F, '$0 ~/artifact,0,id/ {print $6}')
          echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV

      - name: Trigger Terraform Apply
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_ami_id: ${{ env.AMI_ID }}
